//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetailsTable
    {
        public int BookingID { get; set; }
        public int EquipmentID { get; set; }
        public System.DateTime Date { get; set; }
        public string ICNumber { get; set; }
        public int Slot { get; set; }
    }
}
