//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotAvailability
    {
        public int SlotAvailID { get; set; }
        public System.DateTime Date { get; set; }
        public int EquipmentID { get; set; }
        public Nullable<int> Slot1 { get; set; }
        public Nullable<int> Slot2 { get; set; }
        public Nullable<int> Slot3 { get; set; }
        public Nullable<int> Slot4 { get; set; }
        public Nullable<int> Slot5 { get; set; }
        public Nullable<int> Slot6 { get; set; }
        public Nullable<int> Slot7 { get; set; }
        public Nullable<int> Slot8 { get; set; }
        public Nullable<int> Slot9 { get; set; }
        public Nullable<int> Slot10 { get; set; }
        public Nullable<int> Slot11 { get; set; }
        public Nullable<int> Slot12 { get; set; }
    }
}
