//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsFacilityDetail
    {
        public int EquipmentID { get; set; }
        public string EqipmentName { get; set; }
        public int EquipmentCount { get; set; }
        public string AllowNonMembers { get; set; }
        public Nullable<int> NonMemberCount { get; set; }
    }
}
